core/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('', include('home.urls')),
    url('admin-sgep/', admin.site.urls),
    url('alumnos/', include('alumnos.urls')),

    url('estancias/', include('estancias.urls')),
    url('organizaciones/', include('organizaciones.urls')),

]

home/urls.py
from django.conf.urls import url
from .views import *

from alumnos.views import change_password

from django.contrib.auth.forms import AdminPasswordChangeForm


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # url de periodos
    url(r'^periodos/$', PeridoListView.as_view(), name='periodos_list'),
    url(r'^periodos/agregar$', PeridoCreateView.as_view(), name='periodos_new'),
    url(r'^periodos/(?P<pk>\d+)/editar/$', PeridoUpdateView.as_view(), name='periodos_update'),
    url(r'^periodos/(?P<pk>\d+)/eliminar/$', PeridoDeleteView.as_view(), name='periodos_delete'),

]

estancias/models.py
from django.db import models
from campus.models import Student, Profile, Career,Days
from organizaciones.models import Organization


class Requirements(models.Model):

    title = models.CharField(max_length=100, verbose_name='Título', default='', blank=True)
    description = models.TextField(max_length=500, default='', blank=True, verbose_name='Descripción')
    status = models.BooleanField(default=False, verbose_name='Activo')
    career = models.ForeignKey(Career, blank=True, default="")

    class Meta:
        verbose_name = " Requisito"
        verbose_name_plural = "Requisitos"

    def __str__(self):
        return self.title


class Stays(models.Model):

    KIND_STAY = (
        ('A', 'Área'),
        ('P', 'Proyecto')
    )

    STATUS = (
        ('C', 'cancelada'),
        ('T', 'terminada'),
        ('P', 'proceso'),

    )
    student = models.ForeignKey(Student, verbose_name='Alumno')
    cordinator = models.ForeignKey(Profile, verbose_name='Encargado dentro de la universidad',blank=True,null=True)
    kind_stay = models.CharField(choices=KIND_STAY, max_length=2,verbose_name='Tipo de estancia')
    description = models.CharField(max_length=500, verbose_name='Nombre de proyecto o Área', default='', blank=True)
    status = models.CharField(max_length=2, choices=STATUS, verbose_name='Estatus de la estancia', default='P')
    date_start = models.DateField(verbose_name='Fecha de inicio')
    date_end = models.DateField(verbose_name='Fecha de terminación', blank=True, null=True, )
    reason_cancel = models.TextField(verbose_name='Razón de cancelación', null=True, blank=True)
    requirements = models.ManyToManyField(Requirements,verbose_name='Requitos',through='ManageRequirements')

    # data dias y horario
    shedule_start = models.TimeField(verbose_name='Horario de entrada', blank=True,null=True)
    shedule_end = models.TimeField(verbose_name='Horario de salida', blank=True,null=True)
    days = models.ManyToManyField(Days, verbose_name='Días de asistencia')
    # data encargado

    title_boss = models.CharField(max_length=50, verbose_name='Título', blank=True, help_text='Lic.')
    name_boss = models.CharField(max_length=200, verbose_name='Nombre ',blank=True)
    lastname_boss= models.CharField(max_length=200, verbose_name='Apellidos',blank=True)
    position_boss = models.CharField(max_length=200, verbose_name='Cargo dentro de la organización', blank=True)
    organization_boss = models.ForeignKey(Organization, on_delete=models.SET_NULL,
                                          blank=True, null=True, verbose_name='Organización')
    departament_boss = models.CharField(max_length=200, verbose_name='Área,Departamento o Dirección',
                                        help_text='Dirección de informática',
                                        blank=True)
    email_boss = models.EmailField(verbose_name='Correo Electrónico', blank=True, null=True)
    phone_boss = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=20)
    ext_boss = models.CharField(verbose_name='Extensión', blank=True, null=True, max_length=20)

    class Meta:

        verbose_name = " Estancia"
        verbose_name_plural = "Estancias"

    def __str__(self):
        return "{0}".format(self.student)


class ManageRequirements(models.Model):
    stay = models.ForeignKey(Stays, on_delete=models.CASCADE, verbose_name='Estancia')
    requirement = models.ForeignKey(Requirements, on_delete=models.CASCADE, verbose_name='Requisito')
    is_cover = models.BooleanField(default=False, verbose_name='Cubierto')

    class Meta:
        verbose_name = 'Requisito de estancia'
        verbose_name_plural = 'Requisitos de estancia'

    def __str__(self):

        return '({0}) {1}'.format('Cubierto' if self.is_cover else 'Faltante', self.requirement)


class Projects(models.Model):

    name = models.CharField(max_length=400, blank=False, verbose_name='Nombre del programa o proyecto')
    boss = models.CharField(max_length=300, verbose_name='Responsable')
    position = models.CharField(max_length=300, verbose_name='Cargo')
    duration = models.CharField(max_length=300, verbose_name='Duración')
    implementation_field = models.CharField(max_length=400, verbose_name='Campo de aplicacíon',
                                            blank=True, null=True,
                                            help_text='En caso de que aplique')

    objetive = models.TextField(max_length=600, verbose_name='Objetivo o finalidad')
    stay = models.ForeignKey(Stays)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Proyecto de estancia'
        verbose_name_plural = 'Proyectos de estancia'

    def __str__(self):
        return self.name


class Areas(models.Model):
    name = models.CharField(max_length=200, verbose_name='Área o Departamento ')
    hours = models.PositiveIntegerField(verbose_name='Horas por actividad')
    activities = models.TextField(max_length=400,verbose_name='Actividades')
    stay = models.ForeignKey(Stays)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import generic
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView
from django.core.urlresolvers import reverse_lazy
from braces.views import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from campus.forms import PeriodosForm, Periods


class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'base.html'
    login_url = 'login'
    raise_exception = True
    redirect_field_name = REDIRECT_FIELD_NAME  # Set by django.contrib.auth
    redirect_unauthenticated_users = True


class LoginView(FormView):

    template_name = 'login.html'
    success_url = reverse_lazy('home')
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.POST.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):

    url = '/login'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class PeridoListView(LoginRequiredMixin,generic.ListView):
    model = Periods
    paginate_by = 15
    template_name = 'periodos/periodos_list.html'
    context_object_name = 'periodos'


class PeridoCreateView(PermissionRequiredMixin, SuccessMessageMixin, generic.CreateView):
    login_url = 'login'
    success_message = 'Se ha registrado con éxito el periodo'
    success_url = reverse_lazy('periodos_list')
    form_class = PeriodosForm
    model = Periods
    permission_required = "periodos.add_periodos"
    template_name = "periodos/periodos_new.html"


class PeridoUpdateView(PermissionRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    login_url = 'login'
    success_message = 'Se ha actualizado  con éxito el periodo'
    success_url = reverse_lazy('periodos_list')
    form_class = PeriodosForm
    model = Periods
    permission_required = "periodos.change_periodos"
    template_name = "periodos/periodos_new.html"


class PeridoDeleteView(PermissionRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    login_url = 'login'
    success_message = 'Se ha eliminado con éxito el periodo'
    success_url = reverse_lazy('periodos_list')
    model = Periods
    permission_required = "periodos.add_periodos"
    template_name = "periodos/periodos_delete.html"

home/templates/405.html
{% extends 'base.html' %}
{% block content %}
        <h3>{{ message }}</h3>
{% endblock content %}

home/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.standalone.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{%  static 'css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
</head>
<body>

    <header class=" container-fluid header-nav-main">
        <nav class="menu-nav">

            <ul class="menu">
                {% if request.user.is_superuser %}
                    {% include 'menu_admin.html' %}


                {% elif request.user.is_student %}
                    {% include 'menu_estudiante.html' %}


                {% elif request.user.is_coordinator %}
                    {% include 'menu_cordinador.html' %}
                {% endif %}

                <li class="menu-item"> <a class="link_menu" href="/logout">Salir</a></li>


            </ul>

        </nav>

    </header>

    <div class="row">
        <div class="col-md-12">
            {% include 'partials/messages.html' %}
        </div>
    </div>
    <div class="container container-main" >
        <div class="row">
            <h4>Bienvenido {{ request.user }}
                <small>{% if request.user.is_student  %}Estudiante{% endif %}</small>
                <small>{% if request.user.is_coordinator  %}Estudiante{% endif %}</small>
                <small>{% if request.user.is_superuser  %}Administrador{% endif %}</small>
            </h4>
        </div>

        <div class="col-12">
            <h4 >{% block title_secction %}{% endblock %}</h4>
            <hr>
            <div class="row mt-4" >

                {% block content %}{% endblock %}
            </div>



      </div>


  </div>



    <!--  javascript --->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="{% static 'js/local_es.min.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %} "></script>
    {% block js %}{% endblock js %}
    <script>

            $('.datepicker').datepicker({language: 'es'});
            $('.timepicker').timepicker({
                timeFormat: 'HH:mm:ss',
                interval: 60,
                minTime: '9',
                maxTime: '23:00pm',
                defaultTime: '24',
                startTime: '09:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
                });

    </script>
</body>
</html>

home/templates/change_password.html
{% extends 'base.html' %}
{% block title %} Edicion alumno {% endblock %}

{% block content %}



    <div class="col-12">
    <h4>Cambio de contraseña</h4>
        <form action="" method="post" class="form-group col-9">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>

    <hr>


{% endblock %}

home/templates/form_errors.html
{% load i18n %}

{% if form.errors %}
   <div class="row">
        <div class="alert alert-danger">
            {{form.errors   }}
        </div>
   </div>
{% endif %}

home/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login Sistema para gestión de practicas profesionales</title>
    {% load static %}
    <link rel="stylesheet" href="{%  static 'css/login.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container">
    <div class="row">


        <div class="form-container col-md-5">

            {%  if form.errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.errors }}
            </div>
        {% endif %}
            <form action="" method="post" class="form col-md-10">
                {% csrf_token %}
                <div class="form-group">
                     <img src="{% static 'img/bannerlogo.jpg' %}"  class="col-12" alt="">
                </div>
                <div class="form-group">


                    <label for="">Usuario:</label><br>
                    <input type="text" name="username" class="form-group col-12">
                </div>
                 <div class="form-group">
                    <label for="">Contraseña:</label> <br>
                    <input type="password" name="password" class="form-group col-12">
                </div>

                <div class="form-group">
                    <input type="submit"  class="btn btn-primary" value="Enviar">
                </div>
            </form>
        </div>


        
        
        
    </div>
</div>



<!--  javascript --->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

home/templates/menu_admin.html
{% load static %}


    <li class="menu-item"><img src="{% static 'img/titulo-uqroo_es.png' %}" class="" alt=""></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Incio</a></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Carreras</a></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'students_list' %}">Alumnos</a></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'organizations_list' %}">Organizaciones</a></li>

    {% comment %}<li class="menu-item"><a class="link_menu" href=" {%  url 'stays_list' %}">Estancias</a></li>{% endcomment %}
    <li class="menu-item"><a class="link_menu" href=" ">Organizaciones</a></li>
    <li class="menu-item"><a class="link_menu" href="">Configuración</a></li>
    <li class="menu-item">Bienvenido  {{ request.user }}</li>

home/templates/menu_cordinador.html
{% load static %}
<li class="menu-item"><img src="{% static 'img/titulo-uqroo_es.png' %}" class="" alt=""></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Incio</a></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'students_list' %}">Alumnos</a></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Estancias</a></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'organizations_list' %}">Organizaciones</a></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Reportes</a></li>
<li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Configuración</a></li>

home/templates/menu_estudiante.html
{% load static %}
    <li class="menu-item"><img src="{% static 'img/titulo-uqroo_es.png' %}" class="" alt=""></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Incio</a></li>
    <li class="menu-item"><a class="link_menu" href=" {%  url 'home' %}">Estancias</a></li>

home/templates/pagination.html
{% if is_paginated %}



    <nav aria-label=" Page navigation" class="col-md-12">
        <ul class="pagination justify-content-center flex-wrap">
          {% if page_obj.has_previous %}
               <li  class="page-item">
                   <a href="?page={{ page_obj.previous_page_number }}&search_text={{q}}" class="page-link">
                       &laquo;
                   </a>
               </li>

          {% else %}
        <li class=" page-item disabled">
          <a href="#"  class="page-link">
                    &laquo;
               </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active page-item"{% endif %}>
          <a href="?page={{ page }}&search_text={{ q }}"  class="page-link">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}&search_text={{ q }}"  class="page-link">
             &raquo;
          </a>
        </li>

      {% else %}
        <li {% if not page_obj.has_next %}class=" page-item disabled"{% endif %}>
          <a href="#"  class="page-link">
             &raquo;
          </a>
        </li>
      {% endif %}
    </ul>
    </nav>


{% endif %}