core/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('', include('home.urls')),
    url('admin-sgep/', admin.site.urls),
    url('alumnos/', include('alumnos.urls')),

    url('estancias/', include('estancias.urls')),
    url('organizaciones/', include('organizaciones.urls')),

]

estancias/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', StaysListView.as_view(), name='stays_list'),
    url(r'^registro_estancia$', RegistryStay.as_view(), name='stays_registro'),

    url(r'^agregar/$', StayCreateView.as_view(), name='stays_new'),
    url(r'^editar/(?P<pk>\d+)/$', StayUpdate.as_view(), name='stays_update'),
]

estancias/models.py
from django.db import models
from campus.models import Student, Profile, Career,Days
from organizaciones.models import Organization


class Requirements(models.Model):

    title = models.CharField(max_length=100, verbose_name='Título', default='', blank=True)
    description = models.TextField(max_length=500, default='', blank=True, verbose_name='Descripción')
    status = models.BooleanField(default=False, verbose_name='Activo')
    career = models.ForeignKey(Career, blank=True, default="")

    class Meta:
        verbose_name = " Requisito"
        verbose_name_plural = "Requisitos"

    def __str__(self):
        return self.title


class Stays(models.Model):

    KIND_STAY = (
        ('A', 'Área'),
        ('P', 'Proyecto')
    )

    STATUS = (
        ('C', 'cancelada'),
        ('T', 'terminada'),
        ('P', 'proceso'),

    )
    student = models.ForeignKey(Student, verbose_name='Alumno')
    cordinator = models.ForeignKey(Profile, verbose_name='Encargado dentro de la universidad',blank=True,null=True)
    kind_stay = models.CharField(choices=KIND_STAY, max_length=2,verbose_name='Tipo de estancia')
    description = models.CharField(max_length=500, verbose_name='Nombre de proyecto o Área', default='', blank=True)
    status = models.CharField(max_length=2, choices=STATUS, verbose_name='Estatus de la estancia', default='P')
    date_start = models.DateField(verbose_name='Fecha de inicio')
    date_end = models.DateField(verbose_name='Fecha de terminación', blank=True, null=True, )
    reason_cancel = models.TextField(verbose_name='Razón de cancelación', null=True, blank=True)
    requirements = models.ManyToManyField(Requirements,verbose_name='Requitos',through='ManageRequirements')

    # data dias y horario
    shedule_start = models.TimeField(verbose_name='Horario de entrada', blank=True,null=True)
    shedule_end = models.TimeField(verbose_name='Horario de salida', blank=True,null=True)
    days = models.ManyToManyField(Days, verbose_name='Días de asistencia')
    # data encargado

    title_boss = models.CharField(max_length=50, verbose_name='Título', blank=True, help_text='Lic.')
    name_boss = models.CharField(max_length=200, verbose_name='Nombre ',blank=True)
    lastname_boss= models.CharField(max_length=200, verbose_name='Apellidos',blank=True)
    position_boss = models.CharField(max_length=200, verbose_name='Cargo dentro de la organización', blank=True)
    organization_boss = models.ForeignKey(Organization, on_delete=models.SET_NULL,
                                          blank=True, null=True, verbose_name='Organización')
    departament_boss = models.CharField(max_length=200, verbose_name='Área,Departamento o Dirección',
                                        help_text='Dirección de informática',
                                        blank=True)
    email_boss = models.EmailField(verbose_name='Correo Electrónico', blank=True, null=True)
    phone_boss = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=20)
    ext_boss = models.CharField(verbose_name='Extensión', blank=True, null=True, max_length=20)

    class Meta:

        verbose_name = " Estancia"
        verbose_name_plural = "Estancias"

    def __str__(self):
        return "{0}".format(self.student)


class ManageRequirements(models.Model):
    stay = models.ForeignKey(Stays, on_delete=models.CASCADE, verbose_name='Estancia')
    requirement = models.ForeignKey(Requirements, on_delete=models.CASCADE, verbose_name='Requisito')
    is_cover = models.BooleanField(default=False, verbose_name='Cubierto')

    class Meta:
        verbose_name = 'Requisito de estancia'
        verbose_name_plural = 'Requisitos de estancia'

    def __str__(self):

        return '({0}) {1}'.format('Cubierto' if self.is_cover else 'Faltante', self.requirement)


class Projects(models.Model):

    name = models.CharField(max_length=400, blank=False, verbose_name='Nombre del programa o proyecto')
    boss = models.CharField(max_length=300, verbose_name='Responsable')
    position = models.CharField(max_length=300, verbose_name='Cargo')
    duration = models.CharField(max_length=300, verbose_name='Duración')
    implementation_field = models.CharField(max_length=400, verbose_name='Campo de aplicacíon',
                                            blank=True, null=True,
                                            help_text='En caso de que aplique')

    objetive = models.TextField(max_length=600, verbose_name='Objetivo o finalidad')
    stay = models.ForeignKey(Stays)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Proyecto de estancia'
        verbose_name_plural = 'Proyectos de estancia'

    def __str__(self):
        return self.name


class Areas(models.Model):
    name = models.CharField(max_length=200, verbose_name='Área o Departamento ')
    hours = models.PositiveIntegerField(verbose_name='Horas por actividad')
    activities = models.TextField(max_length=400,verbose_name='Actividades')
    stay = models.ForeignKey(Stays)

estancias/forms.py
from django import forms
from .models import Stays, Areas, Projects,Days
from django.conf import settings
from campus.models import Profile


class StayForm(forms.ModelForm):

    days = forms.ModelMultipleChoiceField(label='Días de trabajo',queryset=Days.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}))

    class Meta:
        model = Stays
        fields = ['student', 'cordinator', 'kind_stay', 'description', 'status', 'date_start', 'date_end',
                  'title_boss', 'name_boss', 'lastname_boss', 'position_boss', 'organization_boss', 'departament_boss',
                  'email_boss', 'phone_boss', 'ext_boss','shedule_start','shedule_end','days']
        widgets = {


            'kind_stay': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'date_start': forms.DateInput(format="%d/%m%/%Y", attrs={'class': 'form-control datepicker'}),
            'date_end': forms.DateInput(format="%d/%m%/%Y", attrs={'class': 'form-control datepicker'}),
            'shedule_start': forms.TimeInput(attrs={'class': 'form-control timepicker'}),
            'shedule_end': forms.TimeInput(attrs={'class': 'form-control timepicker'}),

            'reason_cancel': forms.Textarea(attrs={'class': 'form-control'}),
            # data cordinator

            'title_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'name_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'lastname_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'position_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'organization_boss': forms.Select(attrs={'class': 'form-control'}),
            'departament_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'email_boss': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_boss': forms.TextInput(attrs={'class': 'form-control'}),
            'ext_boss': forms.TextInput(attrs={'class': 'form-control'}),



        }

estancias/views.py
from django.shortcuts import render
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from .models import Stays,Days
from django.contrib.messages.views import SuccessMessageMixin
from .forms import StayForm


class StaysListView(generic.ListView):
    model = Stays
    template_name = 'stays_list.html'
    context_object_name = 'estancias'
    queryset = Stays.objects.all()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        if self.request.user.is_coordinator:
            context['estancias'] = Stays.objects.filter(student__career_id=self.request.user.profile.career_id,
                                                        student__campus_id=self.request.user.profile.campus_id)
        elif self.request.user.is_student:
            context['estancias'] = Stays.objects.filter(student=self.request.user.student)
        else:
            context['estancias'] = Stays.objects.all()
        return context


class StayCreateView(SuccessMessageMixin, generic.CreateView):
    model = Stays
    template_name = 'stays_create.html'
    success_url = reverse_lazy('stays_list')
    form_class = StayForm
    success_message = ' Se ha creado la estancia con éxito'

    def get(self, request, *args, **kwargs):
        get = super(StayCreateView, self).get(request,args,kwargs)

        if self.request.user.is_student:
            if self.request.user.student.stays_set.filter(status='P').count() > 1:
                return render(request, template_name="405.html", context={'message':'No puedes registrar una estancia si ya tienes una en proceso'},status=405)
        else:
            return get

    def get_context_data(self, **kwargs):

        context = super(StayCreateView, self).get_context_data(**kwargs)

        if self.request.user.is_student:
            context['student'] = self.request.user.id
            context['coordinator'] = self.request.user.student.get_cordinator().pk
            context['days'] = Days.objects.all()

        return context


class StayUpdate(SuccessMessageMixin, generic.UpdateView):
    model = Stays
    template_name = 'stays_create.html'
    success_url = reverse_lazy('stays_list')
    form_class = StayForm
    success_message = ' Se ha actualizado la estancia con éxito'


class StaysDelete(SuccessMessageMixin, generic.DeleteView):
    model = Stays
    template_name = 'stays_delete.html'
    success_url = reverse_lazy('stays_list')
    success_message = ' Se ha eliminado la estancia con éxito'


class RegistryStay(generic.TemplateView):
    template_name = 'documentos/registro_estancia.html'

estancias/templates/stays_create.html
{% extends 'base.html' %}
{% block title %} Registro de estancia {% endblock %}

{% block content %}


    {% include 'form_errors.html' %}

    <form action="" method="post" class="form-group col-9">
        {% csrf_token %}

        <fieldset>
            <legend>Datos de la estancia</legend>
            <input type="hidden" id="id_student" name="student" value="{{ student }}">
            <input type="hidden" id="id_coordinator" name="cordinator" value="{{ coordinator }}">
            <input type="hidden" id="id_status" name="status" value="P">
            <div class="form-group">
                {{ form.kind_stay.label_tag }}
                {{ form.kind_stay }}
            </div>

            <div class="form-group">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>


            <div class="form-group ">
                {{ form.date_start.label_tag }}
                {{ form.date_start }}
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    {{ form.shedule_start.label_tag }}
                    {{ form.shedule_start }}
                </div>

                <div class="form-group col-md-6">
                    {{ form.shedule_end.label_tag }}
                    {{ form.shedule_end }}
                </div>



            </div>


            <div class="form-group col-md-12 ">
            {{ form.days.label_tag }}<br>
                {% for d in days %}
                    <div class="form-check form-check-inline col-md-3">
                        <input class="form-check-input" type="checkbox" id="day{{ d.pk }}" value="{{ d.pk }}">
                        <label class="form-check-label" for="day{{ d.pk }}">{{ d.day_name }}</label>
                    </div>
                {% endfor %}
            </div>

        </fieldset>
        <fieldset>
            <legend>Datos del encargado</legend>
            <div class="row">
                <div class="form-group col-md-3">
                    {{ form.title_boss.label_tag }}
                    {{ form.title_boss }}
                    {{ form.title_boss.help_text }}
                </div>
                <div class="form-group col-md-9">
                    {{ form.name_boss.label_tag }}
                    {{ form.name_boss }}
                </div>
            </div>

            <div class="row">

                <div class="form-group col-md-12">
                    {{ form.lastname_boss.label_tag }}
                    {{ form.lastname_boss }}
                </div>
            </div>
            <div class="form-group">
                {{ form.position_boss.label_tag }}
                {{ form.position_boss }}
            </div>

            <div class="form-group">
                {{ form.organization_boss.label_tag }}
                {{ form.organization_boss }}
            </div>

            <div class="form-group">
                {{ form.departament_boss.label_tag }}
                {{ form.departament_boss }}
            </div>

            <div class="form-group">
                {{ form.email_boss.label_tag }}
                {{ form.email_boss }}
            </div>

            <div class="row">
                <div class="form-group col-md-5">
                    {{ form.phone_boss.label_tag }}
                    {{ form.phone_boss }}
                </div>
                <div class="form-group col-md-5">
                    {{ form.ext_boss.label_tag }}
                    {{ form.ext_boss }}
                </div>
            </div>
        </fieldset>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
    </form>


{% endblock %}

estancias/templates/stays_delete.html
{% extends 'base.html' %}
{% block title %} Eliminar  a alumno {% endblock %}

{% block content %}


    {% if allowed %}
    <form action="" method="post" class="form-group col-9">
        {% csrf_token %}
        <p>¿Está seguro de eliminar esta estancia? , si elimina este registro se perderán estos datos:</p>

        <ul>
            <li>{{ object}}</li>
        </ul>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
    {% else %}

        <h3>No tiene los permisos suficientes para eliminar este registro</h3>
    {% endif %}


{% endblock %}

estancias/templates/stays_list.html
{% extends 'base.html' %}
{% block title %} Listado de estancias {% endblock %}

{% block content %}
    
    <div class="col-md-10">
        <a href="{% url 'stays_new' %}" class="btn btn-success">Agregar Estancia</a>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Alumno</th>
                <th scope="col">Area o proyecto</th>
                <th scope="col">Estatus</th>
                <th scope="col">Fechas</th>
                <th scope="col">Encargado</th>

                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for e in estancias %}
            <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.student }}</td>
                <td>{{ e.description }}</td>
                <td>{{ e.get_status_display }} {{ e.lastname_mother }}</td>
                <td>{{ e.date_start }} - {{ e.date_end }}</td>
                <td>{{ e.boss }}</td>

                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Acciones
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'stays_update' e.pk %}">Editar</a>

                        {% if e.student.campus_id == request.user.profile.campus_id and e.student.career_id ==  request.user.profile.career_id  or request.user.is_superuser %}
                          <a class="dropdown-item " href="{% url 'students_delete'  e.pk %}">Eliminar</a>
                        {% endif %}


                        <a class="dropdown-item" href="#">Doc presentación</a>
                        <a class="dropdown-item" href="#">Doc Terminación</a>

                      </div>
                    </div>

                </td>
            </tr>
        {%endfor%}

      </tbody>
    </table>

    {% include 'pagination.html' %}


{% endblock %}

estancias/templates/stays_update.html
{% extends 'base.html' %}
{% block title %} Registro de estancia {% endblock %}

{% block content %}


    {% include 'form_errors.html' %}

    <form action="" method="post" class="form-group col-9">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>


{% endblock %}