core/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('', include('home.urls')),
    url('admin-sgep/', admin.site.urls),
    url('alumnos/', include('alumnos.urls')),

    url('estancias/', include('estancias.urls')),
    url('organizaciones/', include('organizaciones.urls')),

]

organizaciones/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    # Rutas Organizaciones
    url(r'^$',OrganizationListView.as_view(), name='organizations_list'),
    url(r'^agregar/$',OrganizationCreateView.as_view(), name='organizations_new'),
    url(r'^editar/(?P<pk>\d+)/$', OrganizacionUpdateView.as_view(), name='organizations_update'),
    url(r'^(?P<pk>\d+)/$', OrganizationDetail.as_view(), name='organizations_detail'),

    # Rutas tipo organizacion
    url(r'^tipo-organizacion/agregar/$', TypeOrganizationCreateView.as_view(), name='type_organization_new'),
    url(r'^tipo-organizacion/editar/(?P<pk>\d+)/$', TypeOrganizationUpdateView.as_view(), name='type_organization_update'),
    url(r'^tipo-organizacion/$', TypoOrganizationList.as_view(), name='type_organization_list'),


]

estancias/models.py
from django.db import models
from campus.models import Student, Profile, Career,Days
from organizaciones.models import Organization


class Requirements(models.Model):

    title = models.CharField(max_length=100, verbose_name='Título', default='', blank=True)
    description = models.TextField(max_length=500, default='', blank=True, verbose_name='Descripción')
    status = models.BooleanField(default=False, verbose_name='Activo')
    career = models.ForeignKey(Career, blank=True, default="")

    class Meta:
        verbose_name = " Requisito"
        verbose_name_plural = "Requisitos"

    def __str__(self):
        return self.title


class Stays(models.Model):

    KIND_STAY = (
        ('A', 'Área'),
        ('P', 'Proyecto')
    )

    STATUS = (
        ('C', 'cancelada'),
        ('T', 'terminada'),
        ('P', 'proceso'),

    )
    student = models.ForeignKey(Student, verbose_name='Alumno')
    cordinator = models.ForeignKey(Profile, verbose_name='Encargado dentro de la universidad',blank=True,null=True)
    kind_stay = models.CharField(choices=KIND_STAY, max_length=2,verbose_name='Tipo de estancia')
    description = models.CharField(max_length=500, verbose_name='Nombre de proyecto o Área', default='', blank=True)
    status = models.CharField(max_length=2, choices=STATUS, verbose_name='Estatus de la estancia', default='P')
    date_start = models.DateField(verbose_name='Fecha de inicio')
    date_end = models.DateField(verbose_name='Fecha de terminación', blank=True, null=True, )
    reason_cancel = models.TextField(verbose_name='Razón de cancelación', null=True, blank=True)
    requirements = models.ManyToManyField(Requirements,verbose_name='Requitos',through='ManageRequirements')

    # data dias y horario
    shedule_start = models.TimeField(verbose_name='Horario de entrada', blank=True,null=True)
    shedule_end = models.TimeField(verbose_name='Horario de salida', blank=True,null=True)
    days = models.ManyToManyField(Days, verbose_name='Días de asistencia')
    # data encargado

    title_boss = models.CharField(max_length=50, verbose_name='Título', blank=True, help_text='Lic.')
    name_boss = models.CharField(max_length=200, verbose_name='Nombre ',blank=True)
    lastname_boss= models.CharField(max_length=200, verbose_name='Apellidos',blank=True)
    position_boss = models.CharField(max_length=200, verbose_name='Cargo dentro de la organización', blank=True)
    organization_boss = models.ForeignKey(Organization, on_delete=models.SET_NULL,
                                          blank=True, null=True, verbose_name='Organización')
    departament_boss = models.CharField(max_length=200, verbose_name='Área,Departamento o Dirección',
                                        help_text='Dirección de informática',
                                        blank=True)
    email_boss = models.EmailField(verbose_name='Correo Electrónico', blank=True, null=True)
    phone_boss = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=20)
    ext_boss = models.CharField(verbose_name='Extensión', blank=True, null=True, max_length=20)

    class Meta:

        verbose_name = " Estancia"
        verbose_name_plural = "Estancias"

    def __str__(self):
        return "{0}".format(self.student)


class ManageRequirements(models.Model):
    stay = models.ForeignKey(Stays, on_delete=models.CASCADE, verbose_name='Estancia')
    requirement = models.ForeignKey(Requirements, on_delete=models.CASCADE, verbose_name='Requisito')
    is_cover = models.BooleanField(default=False, verbose_name='Cubierto')

    class Meta:
        verbose_name = 'Requisito de estancia'
        verbose_name_plural = 'Requisitos de estancia'

    def __str__(self):

        return '({0}) {1}'.format('Cubierto' if self.is_cover else 'Faltante', self.requirement)


class Projects(models.Model):

    name = models.CharField(max_length=400, blank=False, verbose_name='Nombre del programa o proyecto')
    boss = models.CharField(max_length=300, verbose_name='Responsable')
    position = models.CharField(max_length=300, verbose_name='Cargo')
    duration = models.CharField(max_length=300, verbose_name='Duración')
    implementation_field = models.CharField(max_length=400, verbose_name='Campo de aplicacíon',
                                            blank=True, null=True,
                                            help_text='En caso de que aplique')

    objetive = models.TextField(max_length=600, verbose_name='Objetivo o finalidad')
    stay = models.ForeignKey(Stays)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Proyecto de estancia'
        verbose_name_plural = 'Proyectos de estancia'

    def __str__(self):
        return self.name


class Areas(models.Model):
    name = models.CharField(max_length=200, verbose_name='Área o Departamento ')
    hours = models.PositiveIntegerField(verbose_name='Horas por actividad')
    activities = models.TextField(max_length=400,verbose_name='Actividades')
    stay = models.ForeignKey(Stays)

organizaciones/models.py
from django.db import models


class TypeOrganization(models.Model):
    name = models.CharField(max_length=200, verbose_name='Tipo de Organizacón')

    class Meta:
        verbose_name = "Tipo Organización"
        verbose_name_plural = "Tipos Organización"

    def __str__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField(max_length=200, verbose_name='Nombre de la organización', unique=True)
    business_name = models.CharField(max_length=200, verbose_name='Razón social', unique=True)
    owner = models.CharField(max_length=400, verbose_name='Titular')
    phone = models.CharField(max_length=30, verbose_name='Teléfono', unique=True)
    type_organization = models.ForeignKey(TypeOrganization, on_delete=models.SET_NULL,
                                          blank=True, null=True, verbose_name='Giro')
    address = models.TextField(verbose_name='Dirección empresa', max_length=300, blank=True, null=True)

    class Meta:
        verbose_name = " Organización"
        verbose_name_plural = "Organizaciones"

    def __str__(self):
        return self.name

organizaciones/forms.py
from django import forms
from .models import Organization, TypeOrganization


class TypeOrganizationForm(forms.ModelForm):

    class Meta:
        model = TypeOrganization
        fields = ['name']
        widget = {
            'name': forms.TextInput(attrs={'class': 'form-control col-12'})
        }


class OrganizationForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ['name', 'business_name', 'owner', 'phone', 'type_organization', 'address']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'business_name': forms.TextInput(attrs={'class': 'form-control'}),
            'owner': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'type_organization': forms.Select(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
        }

organizaciones/views.py
from django.shortcuts import render
from django.views import generic
from .forms import *
from django.core.urlresolvers import reverse_lazy
from .models import *
from estancias.models import Stays

""" CRUD ORGANIZACIONES """


class OrganizationListView(generic.ListView):
    model = Organization
    context_object_name = 'organizations'
    template_name = 'organizations/organizations_list.html'


class OrganizacionUpdateView(generic.UpdateView):

    model = Organization
    success_url = reverse_lazy('organizations_list')
    form_class = OrganizationForm
    template_name = 'organizations/organizations_new.html'


class OrganizationCreateView(generic.CreateView):
    model = Organization
    success_url = reverse_lazy('organizations_list')
    form_class = OrganizationForm
    template_name = 'organizations/organizations_new.html'


class OrganizationDetail(generic.DetailView):
    model = Organization
    context_object_name = 'organization'
    template_name = 'organizations/organizations_detail.html'

    def get_context_data(self, **kwargs):

        data = super().get_context_data(**kwargs)
        data['stays'] = Stays.objects.filter(organization_boss=self.kwargs['pk'])
        return data


""" CRUD TIPO DE ORGANIZACIONES """


class TypoOrganizationList(generic.ListView):
    model = TypeOrganization
    context_object_name = 'tipos'
    success_url = reverse_lazy('type_organization_list')
    template_name = 'type_organization/type_organizations_list.html'


class TypeOrganizationCreateView(generic.CreateView):

    model = TypeOrganization
    success_url = reverse_lazy('type_organization_list')
    form_class = TypeOrganizationForm
    template_name = 'type_organization/type_organization_new.html'


class TypeOrganizationUpdateView(generic.UpdateView):

    model = TypeOrganization
    success_url = reverse_lazy('type_organization_list')
    form_class = TypeOrganizationForm
    template_name = 'type_organization/type_organization_new.html'

organizaciones/templates/organizations/organizations_detail.html
{% extends 'base.html' %}
{% block title %} {{ organization.name }} {% endblock %}
{% block title_secction%} {{ organization }} {% endblock %}

{% block content %}
    <div class="col-md-10 m-4">

        <b>Razón social:</b>  {{ organization.business_name }}<br>
        <b>Titular:</b>  {{ organization.owner }}<br>
        <b>Teléfono:</b>  {{ organization.phone }}<br>
        <b>Tipo de organización:</b>  {{ organization.type_organization }}<br>
        <b>Dirección:</b>  {{ organization.address }}<br>
    </div>

    {% if stays.count%}
    <div class="col-md-10 mt-5">
        <h5>Estancias</h5>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Estudiante</th>
                    <th scope="col">Encargado</th>
                    <th scope="col">Àrea o Depto.</th>
                    <th scope="col">Tipo de estancia</th>
                    <th scope="col">Estatus</th>
                    <th scope="col">Acciones </th>

                </tr>
            </thead>
            <tbody>
            {% for s in  stays %}
                <tr>
                    <td>{{ s.pk }}</td>
                    <td>{{ s.student}} {{ b.lastname }}</td>
                    <td class="col">{{ s.title_boss }} {{ s.name_boss }} {{ s.lastname_boss }}</td>
                    <td>{{ s.departament_boss }}</td>

                    <td>{{ s.get_kind_stay_display}} </td>
                    <td>{{ s.get_status_display}} </td>




                    <td>
                        <div class="dropdown">
                            <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               Acciones
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="">Editar</a>
                          </div>
                        </div>

                    </td>
                </tr>
            {%endfor%}

          </tbody>
        </table>


        </div>

    {% endif %}






{% endblock %}

organizaciones/templates/organizations/organizations_list.html
{% extends 'base.html' %}
{% block title %} Lista de organizaciones {% endblock %}
{% block title_secction%} Tipos de organiazación {% endblock %}

{% block content %}

    <div class="col-md-10">
        <a href="{% url 'organizations_new' %}" class="btn btn-success">Agregar</a>
        <a href="{% url 'type_organization_list' %}" class="btn btn-info">Tipos de Orgnización</a>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Razón social</th>
                <th scope="col">Titular</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Tipo</th>
                <th scope="col">Dirección</th>


            </tr>
        </thead>
        <tbody>
        {% for o in organizations %}
            <tr>
                <td>{{ o.pk }}</td>
                <td>{{ o.business_name }}</td>
                <td>{{ o.owner }}</td>
                <td>{{ o.phone }}</td>
                <td>{{ o.type_organization }}</td>
                <td>{{ o.address }}</td>


                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Acciones
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="{% url 'organizations_detail' pk=o.pk %}">Detalles</a>
                          <a class="dropdown-item" href="{% url 'organizations_update' pk=o.pk %}">Editar</a>
                      </div>
                    </div>

                </td>
            </tr>
        {%endfor%}

      </tbody>
    </table>
    {% include 'pagination.html' %}

{% endblock %}

organizaciones/templates/organizations/organizations_new.html
{% extends 'base.html' %}
{% block title %}Registro de  Organización{% endblock %}
{% block title_secction %}Registro de  Organización{% endblock %}
{% block content %}

    <div class="section col-md-12">
    <form action="" method="post" class=" form-group ">
        {% csrf_token %}
       {{ form.as_p }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
    </div>
{% endblock %}