alumnos/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
   
    url(r'^$',ListStudentsView.as_view(), name='students_list'),
    url(r'^agregar$', CreateStudent.as_view(), name='students_new'),
    url(r'^editar/(?P<pk>\d+)/$', UpdateStudentView.as_view(), name='students_update'),
    url(r'^editar/(?P<pk>\d+)/password$', change_password, name='students_update_password'),
    url(r'^eliminar/(?P<pk>\d+)/$', DeleteStudentView.as_view(), name='students_delete'),


]

core/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('', include('home.urls')),
    url('admin-sgep/', admin.site.urls),
    url('alumnos/', include('alumnos.urls')),

    url('estancias/', include('estancias.urls')),
    url('organizaciones/', include('organizaciones.urls')),

]

alumnos/models.py
from django.db import models

estancias/models.py
from django.db import models
from campus.models import Student, Profile, Career,Days
from organizaciones.models import Organization


class Requirements(models.Model):

    title = models.CharField(max_length=100, verbose_name='Título', default='', blank=True)
    description = models.TextField(max_length=500, default='', blank=True, verbose_name='Descripción')
    status = models.BooleanField(default=False, verbose_name='Activo')
    career = models.ForeignKey(Career, blank=True, default="")

    class Meta:
        verbose_name = " Requisito"
        verbose_name_plural = "Requisitos"

    def __str__(self):
        return self.title


class Stays(models.Model):

    KIND_STAY = (
        ('A', 'Área'),
        ('P', 'Proyecto')
    )

    STATUS = (
        ('C', 'cancelada'),
        ('T', 'terminada'),
        ('P', 'proceso'),

    )
    student = models.ForeignKey(Student, verbose_name='Alumno')
    cordinator = models.ForeignKey(Profile, verbose_name='Encargado dentro de la universidad',blank=True,null=True)
    kind_stay = models.CharField(choices=KIND_STAY, max_length=2,verbose_name='Tipo de estancia')
    description = models.CharField(max_length=500, verbose_name='Nombre de proyecto o Área', default='', blank=True)
    status = models.CharField(max_length=2, choices=STATUS, verbose_name='Estatus de la estancia', default='P')
    date_start = models.DateField(verbose_name='Fecha de inicio')
    date_end = models.DateField(verbose_name='Fecha de terminación', blank=True, null=True, )
    reason_cancel = models.TextField(verbose_name='Razón de cancelación', null=True, blank=True)
    requirements = models.ManyToManyField(Requirements,verbose_name='Requitos',through='ManageRequirements')

    # data dias y horario
    shedule_start = models.TimeField(verbose_name='Horario de entrada', blank=True,null=True)
    shedule_end = models.TimeField(verbose_name='Horario de salida', blank=True,null=True)
    days = models.ManyToManyField(Days, verbose_name='Días de asistencia')
    # data encargado

    title_boss = models.CharField(max_length=50, verbose_name='Título', blank=True, help_text='Lic.')
    name_boss = models.CharField(max_length=200, verbose_name='Nombre ',blank=True)
    lastname_boss= models.CharField(max_length=200, verbose_name='Apellidos',blank=True)
    position_boss = models.CharField(max_length=200, verbose_name='Cargo dentro de la organización', blank=True)
    organization_boss = models.ForeignKey(Organization, on_delete=models.SET_NULL,
                                          blank=True, null=True, verbose_name='Organización')
    departament_boss = models.CharField(max_length=200, verbose_name='Área,Departamento o Dirección',
                                        help_text='Dirección de informática',
                                        blank=True)
    email_boss = models.EmailField(verbose_name='Correo Electrónico', blank=True, null=True)
    phone_boss = models.CharField(verbose_name='Teléfono', blank=True, null=True, max_length=20)
    ext_boss = models.CharField(verbose_name='Extensión', blank=True, null=True, max_length=20)

    class Meta:

        verbose_name = " Estancia"
        verbose_name_plural = "Estancias"

    def __str__(self):
        return "{0}".format(self.student)


class ManageRequirements(models.Model):
    stay = models.ForeignKey(Stays, on_delete=models.CASCADE, verbose_name='Estancia')
    requirement = models.ForeignKey(Requirements, on_delete=models.CASCADE, verbose_name='Requisito')
    is_cover = models.BooleanField(default=False, verbose_name='Cubierto')

    class Meta:
        verbose_name = 'Requisito de estancia'
        verbose_name_plural = 'Requisitos de estancia'

    def __str__(self):

        return '({0}) {1}'.format('Cubierto' if self.is_cover else 'Faltante', self.requirement)


class Projects(models.Model):

    name = models.CharField(max_length=400, blank=False, verbose_name='Nombre del programa o proyecto')
    boss = models.CharField(max_length=300, verbose_name='Responsable')
    position = models.CharField(max_length=300, verbose_name='Cargo')
    duration = models.CharField(max_length=300, verbose_name='Duración')
    implementation_field = models.CharField(max_length=400, verbose_name='Campo de aplicacíon',
                                            blank=True, null=True,
                                            help_text='En caso de que aplique')

    objetive = models.TextField(max_length=600, verbose_name='Objetivo o finalidad')
    stay = models.ForeignKey(Stays)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Proyecto de estancia'
        verbose_name_plural = 'Proyectos de estancia'

    def __str__(self):
        return self.name


class Areas(models.Model):
    name = models.CharField(max_length=200, verbose_name='Área o Departamento ')
    hours = models.PositiveIntegerField(verbose_name='Horas por actividad')
    activities = models.TextField(max_length=400,verbose_name='Actividades')
    stay = models.ForeignKey(Stays)

alumnos/forms.py
from django import forms
from campus.models import *
from django.contrib.auth.forms import UserCreationForm,AdminPasswordChangeForm
from django.db import transaction
from django.contrib.auth.models import Group
from django.http import request


class StudentCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(StudentCreateForm, self).__init__(*args, **kwargs)

    name = forms.CharField(label='Nombre(s)', widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(label='Apellidos', widget=forms.TextInput(attrs={'class': 'form-control'}))
    enrolment = forms.CharField(label='Matrícula', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Correo electrónico', widget=forms.TextInput(attrs={'class': 'form-control'}))
    semester = forms.ModelChoiceField(required=True,
                                      label='Semestre',
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      queryset=Semester.objects.all(),
                                      )

    career = forms.ModelChoiceField(required=True,
                                    widget=forms.Select(attrs={'class': 'form-control'}),
                                    queryset=Career.objects.all(),
                                    label='Licenciatura',
                                    )

    campus = forms.ModelChoiceField(required=True,
                                    widget=forms.Select(attrs={'class': 'form-control'}),
                                    queryset=Campus.objects.all(),
                                    label='Campus'
                                    )
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type':'tel'}),label='Teléfono')
    valid_credits = forms.CharField(label='Créditos Válidos', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta(UserCreationForm.Meta):
        model = User



    @transaction.atomic
    def save(self):

        try:
            students_group = Group.objects.get(name='students')
        except Group.DoesNotExist:
            students_group = Group.objects.create(name='students')

        user = super().save(commit=False)
        user.first_name = self.cleaned_data.get('name')
        user.last_name = self.cleaned_data.get('lastname')
        user.email = self.cleaned_data.get('email')
        user.is_student = True

        user.save()
        students_group.user_set.add(user)
        student = Student()
        student.user = user
        student.enrolment = self.cleaned_data.get('enrolment')
        student.semester = self.cleaned_data.get('semester')
        student.career = self.cleaned_data.get('career')
        student.campus = self.cleaned_data.get('campus')
        student.phone = self.cleaned_data.get('phone')
        student.valid_credits = self.cleaned_data.get('valid_credits')
        student.save()
        return user


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['enrolment', 'semester', 'campus', 'career', 'phone','valid_credits']
        widgets = {

            'enrolment': forms.TextInput(attrs={'class': 'form-control'}),
            'semenster': forms.Select(attrs={'class': 'form-control'}),
            'campus': forms.Select(attrs={'class': 'form-control'}),
            'career':forms.TextInput(attrs={'class': 'form-control'}),
            'valid_credits': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'type': 'tel'}),

        }

alumnos/views.py
from django.shortcuts import render
from campus.models import Student,User
from django.views import generic
from .forms import StudentForm, StudentCreateForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from django.contrib import messages


def change_password(request,pk):
    if request.method == 'POST':
        user = User.objects.get(id=pk)
        form = AdminPasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'La contraseña del usuario {0} ha sido actualizada cón éxito'.format(user))
            return redirect('students_list')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = AdminPasswordChangeForm(request.user)
    return render(request, 'change_password.html',{
        'form': form
    })


class ListStudentsView(generic.ListView):

    template_name = 'alumnos_list.html'
    model = Student
    paginate_by = 15
    queryset = Student.objects.all()
    context_object_name = 'alumnos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_superuser:
            context['alumnos'] = Student.objects.all().order_by('enrolment')
        else:
            context['alumnos'] = Student.objects.filter(career_id=self.request.user.profile.career_id,
                                                        campus_id=self.request.user.profile.campus_id)

        return context



class CreateStudent (generic.CreateView):
    model = Student
    form_class = StudentCreateForm
    success_url = reverse_lazy('students_list')
    template_name = 'alumnos_new.html'


class UpdateStudentView(generic.UpdateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('students_list')
    template_name = 'alumnos_edit.html'


class DeleteStudentView(generic.DeleteView):
    model = Student
    success_url = reverse_lazy('students_list')
    template_name = 'alumnos_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_superuser:
            context['allowed'] = True
        elif self.object.campus_id == self.request.user.profile.campus_id and \
                self.object.career_id == self.request.user.profile.career_id:
            context['allowed'] = True
        else:
            context['allowed'] = False

        return context

alumnos/templates/alumnos_delete.html
{% extends 'base.html' %}
{% block title %} Eliminar  a alumno {% endblock %}

{% block content %}


    {% if allowed %}
    <form action="" method="post" class="form-group col-9">
        {% csrf_token %}
        <p>¿Está seguro de eliminar este alumno? , si elimina este registro se perderán estos datos:</p>

        <ul>
            <li>Las estacias relacionadas con este alumno : {{ object.stays_set.count }}</li>
        </ul>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
    {% else %}

        <h3>No tiene los permisos suficientes para eliminar este registro</h3>
    {% endif %}


{% endblock %}

alumnos/templates/alumnos_edit.html
{% extends 'base.html' %}
{% block title %} Edicion alumno {% endblock %}

{% block content %}



    <div class="col-12">
    <h4>Edición del  alumno {{ object }}</h4>
        <form action="" method="post" class="form-group col-9">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>

    <hr>


{% endblock %}

alumnos/templates/alumnos_list.html
{% extends 'base.html' %}
{% block title %} Alumnos {% endblock %}

{% block content %}
    
    <div class="col-md-10">
        <a href="{% url 'students_new' %}" class="btn btn-success">Agregar Alumno</a>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Matricula</th>
                <th scope="col">Nombre</th>

                <th scope="col">Semestre</th>
                <th scope="col">Carrera</th>
                <th scope="col">Campus</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for a in alumnos %}
            <tr>
                <td>{{ a.pk }}</td>
                <td>{{ a.enrolment }}</td>

                <td>{{ a.user.get_full_name}}</td>
                <td>{{ a.semester }}</td>
                <td>{{ a.career }}</td>
                <td>{{ a.campus }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Acciones
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'students_update' a.pk %}">Editar</a>
                        <a class="dropdown-item" href="#">Ver estancias</a>
                        {% if a.campus_id == request.user.profile.campus_id and a.career_id ==  request.user.profile.career_id  or request.user.is_superuser %}
                          <a class="dropdown-item " href="{% url 'students_delete'  a.pk %}">Eliminar</a>
                        {% endif %}

                      </div>
                    </div>

                </td>
            </tr>
        {%endfor%}

      </tbody>
    </table>
    {% include 'pagination.html' %}

{% endblock %}

alumnos/templates/alumnos_new.html
{% extends 'base.html' %}
{% block title %} Alumnos {% endblock %}

{% block content %}



    <form action="" method="post" class="form-group col-9">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>


{% endblock %}